export const FULL_CONSOLE_ENTRY = {
    name: 'Test',
    console_type: 1,
    model: 'TEST',
    region: 1,
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    company: 'TEST',
    product_condition: 1,
    has_packaging: false,
    is_duplicate: false,
    has_cables: false,
    has_console: true,
    monetary_value: 10.35,
    notes: 'TEST',
}

export const INVALID_CONSOLE_ENTRY = {
    console_type: 1,
    model: 'TEST',
    region: 1,
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    company: 'TEST',
    product_condition: 1,
    has_packaging: false,
    is_duplicate: false,
    has_cables: false,
    has_console: true,
    monetary_value: 10.35,
    notes: 'INVALID',
}

export const FULL_GAME_ENTRY = {
    console_id: 10,
    name: 'TEST',
    edition: 'Original',
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    region: 1,
    developer: 'DEVELOPER',
    publisher: 'PUBLISHER',
    digital: false,
    has_game: true,
    has_manual: true,
    has_box: true,
    is_duplicate: false,
    product_condition: 1,
    monetary_value: 12.34,
    notes: 'FULL HAPPY PATH',
}

export const INVALID_GAME_ENTRY = {
    name: 'TEST',
    edition: 'Original',
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    region: 1,
    developer: 'DEVELOPER',
    publisher: 'PUBLISHER',
    digital: false,
    has_game: true,
    has_manual: true,
    has_box: true,
    is_duplicate: false,
    product_condition: 1,
    monetary_value: 12.34,
    notes: 'INVALID',
}

export const FULL_ACCESSORY_ENTRY = {
    console_id: 10,
    name: 'TEST',
    model: 'Original',
    accessory_type: 1,
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    company: 'COMPANY',
    has_packaging: true,
    product_condition: 1,
    monetary_value: 12.34,
    notes: 'FULL HAPPY PATH',
}

export const INVALID_ACCESSORY_ENTRY = {
    name: 'TEST',
    model: 'Original',
    accessory_type: 1,
    release_date: '1990-01-01',
    bought_date: '1990-01-01',
    company: 'COMPANY',
    has_packaging: true,
    product_condition: 1,
    monetary_value: 12.34,
    notes: 'INVALID',
}

export const ALL_CONSOLES_RESPONSE = [
    {
        id: 10,
        name: 'Test2',
        console_type: 1,
        model: 'TEST',
        region: 1,
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        company: 'TEST',
        product_condition: 1,
        has_packaging: 0,
        is_duplicate: 0,
        has_cables: 0,
        monetary_value: 10.35,
        notes: 'UPDATE',
        has_console: 0,
    },
    {
        id: 12,
        name: 'UPDATE',
        console_type: 1,
        model: null,
        region: 1,
        release_date: null,
        bought_date: null,
        company: null,
        product_condition: 1,
        has_packaging: 0,
        is_duplicate: 0,
        has_cables: 0,
        monetary_value: null,
        notes: null,
        has_console: 0,
    },
    {
        id: 13,
        name: 'Test2',
        console_type: 1,
        model: 'TEST',
        region: 1,
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        company: 'TEST',
        product_condition: 1,
        has_packaging: 0,
        is_duplicate: 0,
        has_cables: 0,
        monetary_value: 10.35,
        notes: 'TEST2',
        has_console: 1,
    },
    {
        id: 14,
        name: 'Test3',
        console_type: 1,
        model: null,
        region: 1,
        release_date: null,
        bought_date: null,
        company: null,
        product_condition: 1,
        has_packaging: 0,
        is_duplicate: 0,
        has_cables: 0,
        monetary_value: null,
        notes: null,
        has_console: 0,
    },
]

export const CONSOLE_INFO_RESPONSE = [
    {
        id: 10,
        name: 'Test2',
        console_type: 1,
        model: 'TEST',
        region: 1,
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        company: 'TEST',
        product_condition: 1,
        has_packaging: 0,
        is_duplicate: 0,
        has_cables: 0,
        monetary_value: 10.35,
        notes: 'UPDATE',
        has_console: 0,
    },
]

export const CREATE_RESPONSE = {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 13,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0,
}

export const UPDATE_RESPONSE = {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '(Rows matched: 1  Changed: 1  Warnings: 0',
    protocol41: true,
    changedRows: 1,
}

export const DELETE_RESPONSE = {
    fieldCount: 0,
    affectedRows: 1,
    insertId: 0,
    serverStatus: 2,
    warningCount: 0,
    message: '',
    protocol41: true,
    changedRows: 0,
}

export const ALL_GAMES_RESPONSE = [
    {
        id: 1,
        console_id: 10,
        name: 'TEST',
        edition: 'Original',
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        region: 1,
        developer: 'DEVELOPER',
        publisher: 'PUBLISHER',
        digital: 0,
        has_game: 1,
        has_manual: 1,
        has_box: 1,
        is_duplicate: 0,
        product_condition: 1,
        monetary_value: 12.34,
        notes: 'FULL HAPPY PATH',
    },
    {
        id: 2,
        console_id: 10,
        name: 'TEST',
        edition: null,
        release_date: null,
        bought_date: null,
        region: 1,
        developer: null,
        publisher: null,
        digital: 0,
        has_game: 1,
        has_manual: 1,
        has_box: 1,
        is_duplicate: 0,
        product_condition: 1,
        monetary_value: null,
        notes: null,
    },
    {
        id: 3,
        console_id: 10,
        name: 'TEST',
        edition: null,
        release_date: null,
        bought_date: null,
        region: 1,
        developer: null,
        publisher: null,
        digital: 0,
        has_game: 1,
        has_manual: 1,
        has_box: 1,
        is_duplicate: 0,
        product_condition: 1,
        monetary_value: null,
        notes: null,
    },
]

export const GAME_INFO_RESPONSE = [
    {
        id: 1,
        console_id: 10,
        name: 'TEST',
        edition: 'Original',
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        region: 1,
        developer: 'DEVELOPER',
        publisher: 'PUBLISHER',
        digital: 0,
        has_game: 1,
        has_manual: 1,
        has_box: 1,
        is_duplicate: 0,
        product_condition: 1,
        monetary_value: 12.34,
        notes: 'FULL HAPPY PATH',
    },
]

export const ALL_ACCESSORIES_RESPONSE = [
    {
        id: 1,
        console_id: 10,
        name: 'TEST',
        model: 'Original',
        accessory_type: 1,
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        company: 'COMPANY',
        product_condition: 1,
        has_packaging: 1,
        monetary_value: 12.34,
        notes: 'FULL HAPPY PATH',
    },
    {
        id: 2,
        console_id: 10,
        name: 'TEST',
        model: null,
        accessory_type: 1,
        release_date: null,
        bought_date: null,
        company: null,
        product_condition: 1,
        has_packaging: 1,
        monetary_value: null,
        notes: null,
    },
]

export const ACCESSORY_INFO_RESPONSE = [
    {
        id: 1,
        console_id: 10,
        name: 'TEST',
        model: 'Original',
        accessory_type: 1,
        release_date: '1990-01-01T05:00:00.000Z',
        bought_date: '1990-01-01T05:00:00.000Z',
        company: 'COMPANY',
        product_condition: 1,
        has_packaging: 1,
        monetary_value: 12.34,
        notes: 'FULL HAPPY PATH',
    },
]

export const BULK_CONSOLE_ENTRIES = [
    [
        'Atari 2600',
        1,
        null,
        1,
        '1977-09-11',
        '2020-01-01',
        'Atari',
        3,
        false,
        false,
        true,
        true,
        25.0,
        'Classic',
    ],
    [
        'Nintendo Entertainment System',
        1,
        null,
        1,
        '1985-10-18',
        '2021-03-15',
        'Nintendo',
        1,
        true,
        false,
        true,
        true,
        45.5,
        'Mint condition',
    ],
    [
        'Sega Genesis',
        1,
        'Model 1',
        1,
        '1989-08-14',
        '2019-11-20',
        'Sega',
        2,
        false,
        true,
        false,
        true,
        30.0,
        'Missing box',
    ],
]

export const BULK_GAME_ENTRIES = [
    [
        1,
        'Pitfall!',
        null,
        '1982-01-01',
        '2020-05-01',
        1,
        'Activision',
        'Activision',
        false,
        true,
        false,
        false,
        false,
        2,
        8.99,
        'Label wear',
    ],
    [
        12,
        'Super Mario Bros.',
        null,
        '1985-10-18',
        '2021-02-14',
        1,
        'Nintendo',
        'Nintendo',
        false,
        true,
        true,
        true,
        false,
        1,
        25.0,
        'Complete in box',
    ],
    [
        10,
        'Sonic the Hedgehog',
        'Original',
        '1991-06-23',
        '2019-08-30',
        1,
        'Sonic Team',
        'Sega',
        false,
        true,
        false,
        false,
        true,
        3,
        15.5,
        'Duplicate copy',
    ],
]

export const BULK_CONSOLE_ID_SEARCH_RESPONSE = [
    { id: 1, name: 'Atari 2600' },
    { id: 2, name: 'Atari 7800' },
    { id: 3, name: 'Atari 8-Bit' },
    { id: 4, name: 'MS-DOS' },
    { id: 5, name: 'Windows 9x' },
    { id: 6, name: 'Windows NT (x86)' },
    { id: 7, name: 'Windows NT (x64)' },
    { id: 8, name: 'Commodore Amiga 500' },
    { id: 9, name: 'Sega Master System' },
    { id: 10, name: 'Sega Genesis' },
    { id: 11, name: 'Sega Game Gear' },
    { id: 12, name: 'Nintendo Entertainment System' },
    { id: 13, name: 'Nintendo Game Boy' },
    { id: 14, name: 'Super Nintendo Entertainment System' },
    { id: 15, name: 'Nintendo 64' },
    { id: 16, name: 'Nintendo GameCube' },
    { id: 17, name: 'Nintendo Game Boy Advance' },
    { id: 18, name: 'Nintendo DS' },
    { id: 19, name: 'Nintendo Wii' },
    { id: 20, name: 'Nintendo Wii U' },
    { id: 21, name: 'Nintendo 3DS XL' },
    { id: 22, name: 'Nintendo Switch' },
    { id: 23, name: 'Sony Playstation' },
    { id: 24, name: 'Sony Playstation 2' },
    { id: 25, name: 'Sony Playstation 3' },
    { id: 26, name: 'Sony Playstation 4' },
    { id: 27, name: 'Microsoft Xbox 360' },
    { id: 28, name: 'Analogue Super NT' },
    { id: 29, name: 'Analogue Mega SG' },
    { id: 30, name: 'Analogue Pocket' },
]

export const EXPECTED_CONSOLE_AND_ID_MAP = {
    'atari 2600': 1,
    'atari 7800': 2,
    'atari 8-bit': 3,
    'ms-dos': 4,
    'windows 9x': 5,
    'windows nt (x86)': 6,
    'windows nt (x64)': 7,
    'commodore amiga 500': 8,
    'sega master system': 9,
    'sega genesis': 10,
    'sega game gear': 11,
    'nintendo entertainment system': 12,
    'nintendo game boy': 13,
    'super nintendo entertainment system': 14,
    'nintendo 64': 15,
    'nintendo gamecube': 16,
    'nintendo game boy advance': 17,
    'nintendo ds': 18,
    'nintendo wii': 19,
    'nintendo wii u': 20,
    'nintendo 3ds xl': 21,
    'nintendo switch': 22,
    'sony playstation': 23,
    'sony playstation 2': 24,
    'sony playstation 3': 25,
    'sony playstation 4': 26,
    'microsoft xbox 360': 27,
    'analogue super nt': 28,
    'analogue mega sg': 29,
    'analogue pocket': 30,
}

export const BULK_ACCESSORY_ENTRIES = [
    [
        1,
        'Atari 2600 Joystick',
        'CX40',
        1,
        '1977-10-01',
        '2020-01-15',
        'Atari',
        3,
        false,
        12.5,
        'Works great',
    ],
    [
        12,
        'NES Controller',
        'NES-004',
        1,
        '1985-10-18',
        '2019-06-01',
        'Nintendo',
        2,
        false,
        15.0,
        null,
    ],
    [
        23,
        'PS1 DualShock',
        'SCPH-1200',
        1,
        '1997-11-01',
        '2020-07-04',
        'Sony',
        2,
        false,
        22.0,
        'Analog sticks tight',
    ],
]
