export const fullConsoleEntry = {
  name: "Test",
  console_type: 1,
  model: "TEST",
  region: 1,
  release_date: "1990-01-01",
  bought_date: "1990-01-01",
  company: "TEST",
  product_condition: 1,
  has_packaging: false,
  is_duplicate: false,
  has_cables: false,
  has_console: true,
  monetary_value: 10.35,
  notes: "TEST",
};

export const fullGameEntry = {
  console_id: 10,
  name: "TEST",
  edition: "Original",
  release_date: "1990-01-01",
  bought_date: "1990-01-01",
  region: 1,
  developer: "DEVELOPER",
  publisher: "PUBLISHER",
  digital: false,
  has_game: true,
  has_manual: true,
  has_box: true,
  is_duplicate: false,
  product_condition: 1,
  monetary_value: 12.34,
  notes: "FULL HAPPY PATH",
};

export const allConsolesResult = [
  {
    id: 10,
    name: "Test2",
    console_type: 1,
    model: "TEST",
    region: 1,
    release_date: "1990-01-01T05:00:00.000Z",
    bought_date: "1990-01-01T05:00:00.000Z",
    company: "TEST",
    product_condition: 1,
    has_packaging: 0,
    is_duplicate: 0,
    has_cables: 0,
    monetary_value: 10.35,
    notes: "UPDATE",
    has_console: 0,
  },
  {
    id: 12,
    name: "UPDATE",
    console_type: 1,
    model: null,
    region: 1,
    release_date: null,
    bought_date: null,
    company: null,
    product_condition: 1,
    has_packaging: 0,
    is_duplicate: 0,
    has_cables: 0,
    monetary_value: null,
    notes: null,
    has_console: 0,
  },
  {
    id: 13,
    name: "Test2",
    console_type: 1,
    model: "TEST",
    region: 1,
    release_date: "1990-01-01T05:00:00.000Z",
    bought_date: "1990-01-01T05:00:00.000Z",
    company: "TEST",
    product_condition: 1,
    has_packaging: 0,
    is_duplicate: 0,
    has_cables: 0,
    monetary_value: 10.35,
    notes: "TEST2",
    has_console: 1,
  },
  {
    id: 14,
    name: "Test3",
    console_type: 1,
    model: null,
    region: 1,
    release_date: null,
    bought_date: null,
    company: null,
    product_condition: 1,
    has_packaging: 0,
    is_duplicate: 0,
    has_cables: 0,
    monetary_value: null,
    notes: null,
    has_console: 0,
  },
];

export const consoleInfoResponse = [
  {
    id: 10,
    name: "Test2",
    console_type: 1,
    model: "TEST",
    region: 1,
    release_date: "1990-01-01T05:00:00.000Z",
    bought_date: "1990-01-01T05:00:00.000Z",
    company: "TEST",
    product_condition: 1,
    has_packaging: 0,
    is_duplicate: 0,
    has_cables: 0,
    monetary_value: 10.35,
    notes: "UPDATE",
    has_console: 0,
  },
];

export const createResult = {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 13,
  serverStatus: 2,
  warningCount: 0,
  message: "",
  protocol41: true,
  changedRows: 0,
};

export const updateResult = {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: "(Rows matched: 1  Changed: 1  Warnings: 0",
  protocol41: true,
  changedRows: 1,
};

export const deleteResult = {
  fieldCount: 0,
  affectedRows: 1,
  insertId: 0,
  serverStatus: 2,
  warningCount: 0,
  message: "",
  protocol41: true,
  changedRows: 0,
};

export const allGamesResponse = [
  {
    id: 1,
    console_id: 10,
    name: "TEST",
    edition: "Original",
    release_date: "1990-01-01T05:00:00.000Z",
    bought_date: "1990-01-01T05:00:00.000Z",
    region: 1,
    developer: "DEVELOPER",
    publisher: "PUBLISHER",
    digital: 0,
    has_game: 1,
    has_manual: 1,
    has_box: 1,
    is_duplicate: 0,
    product_condition: 1,
    monetary_value: 12.34,
    notes: "FULL HAPPY PATH",
  },
  {
    id: 2,
    console_id: 10,
    name: "TEST",
    edition: null,
    release_date: null,
    bought_date: null,
    region: 1,
    developer: null,
    publisher: null,
    digital: 0,
    has_game: 1,
    has_manual: 1,
    has_box: 1,
    is_duplicate: 0,
    product_condition: 1,
    monetary_value: null,
    notes: null,
  },
  {
    id: 3,
    console_id: 10,
    name: "TEST",
    edition: null,
    release_date: null,
    bought_date: null,
    region: 1,
    developer: null,
    publisher: null,
    digital: 0,
    has_game: 1,
    has_manual: 1,
    has_box: 1,
    is_duplicate: 0,
    product_condition: 1,
    monetary_value: null,
    notes: null,
  },
];

export const gameInfoResponse = [
  {
    id: 1,
    console_id: 10,
    name: "TEST",
    edition: "Original",
    release_date: "1990-01-01T05:00:00.000Z",
    bought_date: "1990-01-01T05:00:00.000Z",
    region: 1,
    developer: "DEVELOPER",
    publisher: "PUBLISHER",
    digital: 0,
    has_game: 1,
    has_manual: 1,
    has_box: 1,
    is_duplicate: 0,
    product_condition: 1,
    monetary_value: 12.34,
    notes: "FULL HAPPY PATH",
  },
];
